Support v4 point estimate `required` null values
hubverse-org/hubValidations pull request #160
Opened 2024-11-13 16:11 UTC by annakrystalli

This PR resolves #156 by adding support for `NULL` `required` properties in v4 config for point estimates by effectively converting them to `NA`s in `expand_model_out_grid()`

Overall we're converting v4 configuration to pre v4 configurations which means we leverage previous functionality and ensure back-compatibility. Give task IDs also still use both `required` and `optional` properties, this approach means we handle config values consistently.

I've also tried to start addressing #147 in this PR too.

Just a heads up too that, in the next PR (still in prep), I'm actually re-factoring a little of this as I move on to address #159

2024-11-13 18:59 UTC, zkamvar requested changes
This looks good to me. The catch for v4 point estimates makes sense. I have a few suggestions for readability. 

1. use `round` instead of `rnd`. My brain always wants to convert `rnd` to `random` and we don't currently use `rnd` anywhere.
2. use `setequal()` instead of `isTRUE(all.equal(sort())`.

I also wanted to say that I appreciate the explanatory comments and splitting things into functions. This makes things much easier to read!

2024-11-14 06:42 UTC, annakrystalli commented on R/expand_model_out_grid.R
> +  output_type_l <- subset_rnd_output_types(round_config, output_types) %>%
Sure. Fixed in fef4e3a33527a9df86193bda8b6f88b26ac4bc70

2024-11-14 06:42 UTC, annakrystalli commented on R/expand_model_out_grid.R
> +subset_rnd_output_types <- function(round_config, output_types) {
Sure. Fixed in fef4e3a33527a9df86193bda8b6f88b26ac4bc70

2024-11-14 06:42 UTC, annakrystalli commented on R/expand_model_out_grid.R
> +    extract_rnd_output_type_ids(config_tid) %>%
Sure. Fixed in fef4e3a33527a9df86193bda8b6f88b26ac4bc70

2024-11-14 06:47 UTC, annakrystalli commented on tests/testthat/test-expand_model_out_grid.R
> +  config_tasks <- suppressWarnings(read_config(hub_path = hub_path))
Done in 9fd5fedec06362aee85404c95d3dd2679f1b5145

2024-11-14 07:01 UTC, annakrystalli commented on tests/testthat/test-expand_model_out_grid.R
> +  )
Nice. Added here: ab83e0a8b2dae1a428d2f467ab33e522fd616266

2024-11-14 07:01 UTC, annakrystalli commented on R/expand_model_out_grid.R
> +  )
Thanks! much better. Fixed in 64796e0e9f7ff2dc38796b027ced21e44544b2b9

2024-11-14 07:01 UTC, annakrystalli commented on R/expand_model_out_grid.R
> +  )
Note I had already pulled it out into a function in the next PR

2024-11-14 07:04 UTC, annakrystalli commented
Thanks for the thorough review @zkamvar ! I know it's not ideal but because I'd moved on and done quite a bit of refactoring already in the next PR, I've opted to make the changes in that branch to avoid a messy merge mission.  I've added links to each commit though so you can track the changes. Hope that's ok!

2024-11-14 14:16 UTC, zkamvar approved these changes

2024-11-14 14:19 UTC, merged